app:
  container_name: <product>-app
  build: ./Cabot
  links:
    - db
    - celerybroker
    - smtp
  volumes:
    - /cabot
  env_file: cabot_env

db:
  container_name: <product>-db
  image: postgres
  volumes:
    - /var/lib/cabotdb:/var/lib/postgresql
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker

celerybroker:
  container_name: <product>-broker
  image: redis

smtp:
  container_name: <product>-smtp
  image: tianon/exim4

nginx:
  container_name: <product>-proxy
  image: nginx
  ports:
     - "8000:8000"
  links:
     - app
  volumes_from:
     - app
  volumes:
     - ./Cabot/nginx.conf:/etc/nginx/nginx.conf:ro
